package TCP;

public enum RequestType {
    REGISTER,
    LOGIN,
    VIEW_USERS,
    UPDATE_USER,
    DELETE_USER,
    VIEW_MASTERS,
    ADD_MASTER,
    CREATE_MASTER,
    UPDATE_MASTER,
    DELETE_MASTER,
    VIEW_SERVICES,

    ADD_SERVICE,
    UPDATE_SERVICE,
    DELETE_SERVICE,
    ADD_RECORD,
    UPDATE_RECORD,
    DELETE_RECORD,
    MAKE_REPORT
}
