package TCP;

public enum RequestType {
    REGISTER,
    LOGIN,
    VIEW_USERS,
    ADD_MASTER,
    UPDATE_MASTER,
    DELETE_MASTER,
    ADD_VISITOR,
    UPDATE_VISITOR,
    DELETE_VISITOR,
    ADD_SALON_ADMINISTRATOR,
    UPDATE_SALON_ADMINISTRATOR,
    DELETE_SALON_ADMINISTRATOR,
    ADD_SERVICE,
    UPDATE_SERVICE,
    DELETE_SERVICE,
    ADD_RECORD,
    UPDATE_RECORD,
    DELETE_RECORD,
    MAKE_REPORT
}
