package TCP;

public enum RequestType {
    REGISTER,
    LOGIN,
    VIEW_USERS,
    UPDATE_USER,
    DELETE_USER,
    VIEW_MASTERS,
    ADD_MASTER,
    CREATE_MASTER,
    UPDATE_MASTER,
    DELETE_MASTER,
    VIEW_SERVICES,
    MASTER_LIST,

    ADD_SERVICE,
    UPDATE_SERVICE,
    DELETE_SERVICE,
    FINANCE,
    DELETE_FINANCE,
    UPDATE_FIANCE,
    RECORD,
    ADD_RECORD,
    UPDATE_RECORD,
    DELETE_RECORD,
    SALON_DATA,
    PROFITABILITY,
    VIEW_CLIENT,
    UPDATE_CLIENT,

    MAKE_REPORT
}
